=== spoonless/giweet/src/test/resources/org/giweet/step/tokenizer/StepTokenizerTest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.giweet.org/test/StepTokenizerTest" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.giweet.org/test/StepTokenizerTest">

    <element name="suite" type="tns:suiteType"></element>
    
    <complexType name="suiteType">
    	<sequence>
    		<element name="test" type="tns:testType" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="testType">
    	<sequence>
    		<element name="actual" type="string"></element>
    		<element name="expected" type="tns:expectedType"></element>
    	</sequence>
    	<attribute name="strategy" use="required">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="TOKENIZE_STEP_DESCRIPTOR"></enumeration>
    				<enumeration value="TOKENIZE_SCENARIO"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	
    </complexType>

    <complexType name="expectedType">
    	<sequence>
    		<element name="token" type="tns:tokenType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    </complexType>

    <complexType name="tokenType">
    	<simpleContent>
    		<extension base="string">
		        <attribute name="parameter" type="boolean" default="false"></attribute>
		    	<attribute name="meaningful" type="boolean" default="true"></attribute>
    		</extension>
    	</simpleContent>
    </complexType>
</schema>

=== spoonless/giweet/src/test/resources/org/giweet/step/StepTokenizerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.giweet.org/test/StepTokenizerTest" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.giweet.org/test/StepTokenizerTest StepTokenizerTest.xsd ">
  <test>
    <actual>       </actual>
    <expected>
    </expected>
  </test>
  <test>
    <actual>hello the world</actual>
    <expected>
      <token>hello</token>
      <token>the</token>
      <token>world</token>
    </expected>
  </test>
  <test withMeaninglessTokens="true">
    <actual>hello the world</actual>
    <expected>
      <token>hello</token>
      <token meaningful="false"> </token>
      <token>the</token>
      <token meaningful="false"> </token>
      <token>world</token>
    </expected>
  </test>
  <test>
    <actual>hello the $world</actual>
    <expected>
      <token>hello</token>
      <token>the</token>
      <token>$world</token>
    </expected>
  </test>
  <test allowParameterTokens="true">
    <actual>hello the $world</actual>
    <expected>
      <token>hello</token>
      <token>the</token>
      <token parameter="true">$world</token>
    </expected>
  </test>
  <test withMeaninglessTokens="true">
    <actual>hello the "sunny shiny", world</actual>
    <expected>
      <token>hello</token>
      <token meaningful="false"> </token>
      <token>the</token>
      <token meaningful="false"> </token>
      <token>sunny shiny</token>
      <token meaningful="false">, </token>
      <token>world</token>
    </expected>
  </test>
  <test withMeaninglessTokens="true">
    <actual>hello the sunny"shiny"world</actual>
    <expected>
      <token>hello</token>
      <token meaningful="false"> </token>
      <token>the</token>
      <token meaningful="false"> </token>
      <token>sunny"shiny"world</token>
    </expected>
  </test>
  <test>
    <actual>""</actual>
    <expected>
      <token></token>
    </expected>
  </test>
</suite>

=== spoonless/giweet/src/test/resources/org/giweet/step/tokenizer/StepTokenizerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<suite xmlns="http://www.giweet.org/test/StepTokenizerTest"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.giweet.org/test/StepTokenizerTest StepTokenizerTest.xsd ">

	<test>
		<actual></actual>
		<expected>
		</expected>
	</test>

	<test>
		<actual> </actual>
		<expected>
			<token type="separator"></token>
		</expected>
	</test>

	<test>
		<actual>hello</actual>
		<expected>
			<token>hello</token>
		</expected>
	</test>

	<test>
		<actual>hello the world</actual>
		<expected>
			<token>hello</token>
			<token type="separator"></token>
			<token>the</token>
			<token type="separator"></token>
			<token>world</token>
		</expected>
	</test>

	<test>
		<actual>           hello         the world      </actual>
		<expected>
			<token type="separator"></token>
			<token>hello</token>
			<token type="separator"></token>
			<token>the</token>
			<token type="separator"></token>
			<token>world</token>
			<token type="separator"></token>
		</expected>
	</test>

	<test>
		<actual>100 € 100€</actual>
		<expected>
			<token>100</token>
			<token type="separator"></token>
			<token>€</token>
			<token type="separator"></token>
			<token>100€</token>
		</expected>
	</test>

	<test>
		<actual>1,</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
		</expected>
	</test>

	<test>
		<actual>1, 2</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
			<token>2</token>
		</expected>
	</test>

	<test>
		<actual>1,2</actual>
		<expected>
			<token>1,2</token>
		</expected>
	</test>

	<test>
		<actual>1,,2</actual>
		<expected>
			<token>1,,2</token>
		</expected>
	</test>

	<test>
		<actual>,,2</actual>
		<expected>
			<token type="separator">,</token>
			<token type="separator">,</token>
			<token>2</token>
		</expected>
	</test>

	<test>
		<actual>1,, 2</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
			<token type="separator">,</token>
			<token>2</token>
		</expected>
	</test>

	<test>
		<actual>1 ,, 2</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
			<token type="separator">,</token>
			<token>2</token>
		</expected>
	</test>

	<test>
		<actual>1 , , 2</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
			<token type="separator">,</token>
			<token>2</token>
		</expected>
	</test>

	<test>
		<actual>a'b</actual>
		<expected>
			<token>a</token>
			<token type="separator">'</token>
			<token>b</token>
		</expected>
	</test>

	<test>
		<actual>1, 2: 3; 4! 5. 6? 7' 8	9
    10</actual>
		<expected>
			<token>1</token>
			<token type="separator">,</token>
			<token>2</token>
			<token type="separator">:</token>
			<token>3</token>
			<token type="separator">;</token>
			<token>4</token>
			<token type="separator">!</token>
			<token>5</token>
			<token type="separator">.</token>
			<token>6</token>
			<token type="separator">?</token>
			<token>7</token>
			<token type="separator">'</token>
			<token>8</token>
			<token type="separator"></token>
			<token>9</token>
			<token type="separator"></token>
			<token>10</token>
		</expected>
	</test>

	<test>
		<actual>@hello/the#world*</actual>
		<expected>
			<token>@hello/the#world*</token>
		</expected>
	</test>

	<test>
		<actual> [hello] </actual>
		<expected>
			<token type="separator">[</token>
			<token>hello</token>
			<token type="separator">]</token>
		</expected>
	</test>

	<test>
		<actual>hello[world]</actual>
		<expected>
			<token>hello</token>
			<token type="separator">[</token>
			<token>world</token>
			<token type="separator">]</token>
		</expected>
	</test>

	<test>
		<actual>it's ok</actual>
		<expected>
			<token>it</token>
			<token type="separator">'</token>
			<token>s</token>
			<token type="separator"></token>
			<token>ok</token>
		</expected>
	</test>

	<test>
		<actual>it＇s ok</actual>
		<expected>
			<token>it</token>
			<token type="separator">＇</token>
			<token>s</token>
			<token type="separator"></token>
			<token>ok</token>
		</expected>
	</test>

	<test>
		<actual>http://localhost:8080/mywebsite/</actual>
		<expected>
			<token>http://localhost:8080/mywebsite/</token>
		</expected>
	</test>

	<test>
		<actual>""</actual>
		<expected>
			<token></token>
		</expected>
	</test>

	<test>
		<actual>" "</actual>
		<expected>
			<token> </token>
		</expected>
	</test>

	<test>
		<actual>"hello the world"</actual>
		<expected>
			<token>hello the world</token>
		</expected>
	</test>

	<test>
		<actual>«hello the world»</actual>
		<expected>
			<token>hello the world</token>
		</expected>
	</test>

	<test>
		<actual>«««hello the world»»»</actual>
		<expected>
			<token>««hello the world»»</token>
		</expected>
	</test>

	<test>
		<actual>hello « the world »</actual>
		<expected>
			<token>hello</token>
			<token type="separator"></token>
			<token> the world </token>
		</expected>
	</test>

	<test>
		<actual>«hello the world» "   "</actual>
		<expected>
			<token>hello the world</token>
			<token type="separator"></token>
			<token>   </token>
		</expected>
	</test>

	<test>
		<actual>«"»</actual>
		<expected>
			<token>"</token>
		</expected>
	</test>

	<test>
		<actual>hello ‘ the world ’</actual>
		<expected>
			<token>hello</token>
			<token type="separator"></token>
			<token> the world </token>
		</expected>
	</test>

	<test>
		<actual>hello “ the world ”</actual>
		<expected>
			<token>hello</token>
			<token type="separator"></token>
			<token> the world </token>
		</expected>
	</test>

	<test>
		<actual>hello ‹ the world ›</actual>
		<expected>
			<token>hello</token>
			<token type="separator"></token>
			<token> the world </token>
		</expected>
	</test>

	<test>
		<actual>{}</actual>
		<expected>
			<token type="separator">{</token>
			<token type="separator">}</token>
		</expected>
	</test>

	<test>
		<actual> {} </actual>
		<expected>
			<token type="separator">{</token>
			<token type="separator">}</token>
		</expected>
	</test>

	<test>
		<actual>{0}</actual>
		<expected>
			<token type="dynamic">0</token>
		</expected>
	</test>

	<test>
		<actual> {0}</actual>
		<expected>
			<token type="separator"></token>
			<token type="dynamic">0</token>
		</expected>
	</test>

	<test>
		<actual>a{0}b</actual>
		<expected>
			<token>a</token>
			<token type="dynamic">0</token>
			<token>b</token>
		</expected>
	</test>

	<test>
		<actual>{0000</actual>
		<expected>
			<token type="separator">{</token>
			<token>0000</token>
		</expected>
	</test>

	<test>
		<actual> {0000</actual>
		<expected>
			<token type="separator">{</token>
			<token>0000</token>
		</expected>
	</test>
</suite>
